/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projet.cpoo;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class AppTest {
    
    @Test void appHasAGreeting() {
        assertEquals("a", "b");
    }
}

