/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projet.cpoo;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

import projet.cpoo.Model.EntrainementModel;

class AppTest {
    
    @Test void testIsModeTemps() {
        Settings.setModeTemps();
        EntrainementModel model = new EntrainementModel();
        model.initialize();
        assertEquals(true, model.isModeTemps());
    }

    @Test void testIsModeMots() {
        Settings.setModeMots();
        EntrainementModel model = new EntrainementModel();
        model.initialize();
        assertEquals(false, model.isModeTemps());
    }

    @Test void testInitModeMots() {
        Settings.setModeMots();
        EntrainementModel model = new EntrainementModel();
        model.initialize();
        assert(model.getListeMots().size() > 0);
    }

    @Test void testInitModeTemps() {
        Settings.setModeTemps();
        EntrainementModel model = new EntrainementModel();
        model.initialize();
        assert(model.getListeMots().size() > 0);
    }

    @Test void testStartModeTemps() {
        Settings.setModeTemps();
        EntrainementModel model = new EntrainementModel();
        model.initialize();
        assert(model.isEnJeu());
    }

    @Test void testStartModeMots() {
        Settings.setModeMots();
        EntrainementModel model = new EntrainementModel();
        model.initialize();
        assert(model.isEnJeu());
    }
}

