package projet.cpoo;

public enum Transmission {
    SERVEUR_DECONNEXION,SERVEUR_PERDU,SERVEUR_GAGNER,SERVEUR_OPTION,SERVEUR_CONNEXION,SERVEUR_LANCER,SERVEUR_LISTE_MOT,
    CLIENT_LANCER,CLIENT_OPTION,CLIENT_CONNEXION,CLIENT_DECONNEXION,CLIENT_TEST_CONNEXION
}
